export const saludos = [
    "Hola",
    "HOLA",
    "ola",
    "Ola",
    "Holaa",
    "Holaaa",
    "Hola!",
    "hola!",
    "Buenas",
    "buenas",
    "Buenas tardes",
    "buenas tardes",
    "Buenas noches",
    "buenas noches",
    "Buenos días",
    "buenos días",
    "buen dia",
    "Buen día",
    "Que tal",
    "qué tal",
    "k tal",
    "Q tal",
    "Hi",
    "hello",
    "helo",
    "holis",
    "holiss",
    "holaaa",
    "holap",
    "alo",
    "aloha",
    "saludos",
    "saludo",
    "buenas!",
    "buenass",
    "wenas",
    "wenass",
    "holu",
    "holuwu",
    "holiwis"
].map(saludo => saludo.toLowerCase());;
